version: "3"

services: 
      
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123098
      - POSTGRES_USER=postgres
      - POSTGRES_DB=local
    volumes:
      - ./pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
